### ISSUE TITLE
Easy way to import next meetup

### ISSUE THREAD

**Issue by badboy** [berlinrs/berline.rs#19]
It's currently a manual process to import and deploy the next meetup.
Can we have a script that can do it?

**Comment by skade** [comment]
The main problem here is that meetup doesn't have submeetups (we can only trail OpenTechSchool on Meetup and need to figure out the ones that apply to us). We totally can have that, though!

**Comment by badboy** [comment]
Well, so far we have a pretty simple naming scheme, so we might be able to just match on that?

**Comment by badboy** [comment]
There's now an import script. It's not automatic, but it can pull in data if you provide a meetup.com event url.
It does so by scraping the website, as the API is now behind OAuth.
